Import('env')

env.InstallFrontend(['layout.html', 'index.html', 'help.html', 'faq.html',
                     'running.html', 'results_ok.html',
                     'results_failed.html', 'download.html'], 'templates')
